name = "EconomicToolkit"
uuid = "7c9e1234-5678-90ab-cdef-123456789abc"
authors = ["Hyperpolymath"]
version = "2.0.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
SQLite = "0aa819cd-b072-5ca4-8fd4-e0e014ffd12d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP_jll = "1be8b2c1-0df2-5e3e-bf7c-fc1e6f23aa1a"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"

[compat]
julia = "1.10"
HTTP = "1.10"
JSON3 = "1.14"
SQLite = "1.6"
DataFrames = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[targets]
test = ["Test", "BenchmarkTools"]
